# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/work-Lab/USTCRVSoC/hardware/Vivado/nexys4/USTCRVSoC-nexys4/USTCRVSoC-nexys4.cache/wt [current_project]
set_property parent.project_path E:/work-Lab/USTCRVSoC/hardware/Vivado/nexys4/USTCRVSoC-nexys4/USTCRVSoC-nexys4.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/work-Lab/USTCRVSoC/hardware/Vivado/nexys4/USTCRVSoC-nexys4/USTCRVSoC-nexys4.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  E:/work-Lab/USTCRVSoC/hardware/RTL/core_alu.sv
  E:/work-Lab/USTCRVSoC/hardware/RTL/core_bus_wrapper.sv
  E:/work-Lab/USTCRVSoC/hardware/RTL/core_ex_branch_judge.sv
  E:/work-Lab/USTCRVSoC/hardware/RTL/core_id_stage.sv
  E:/work-Lab/USTCRVSoC/hardware/RTL/core_regfile.sv
  E:/work-Lab/USTCRVSoC/hardware/RTL/core_top.sv
  E:/work-Lab/USTCRVSoC/hardware/RTL/instr_rom.sv
  E:/work-Lab/USTCRVSoC/hardware/RTL/isp_uart.sv
  E:/work-Lab/USTCRVSoC/hardware/RTL/naive_bus.sv
  E:/work-Lab/USTCRVSoC/hardware/RTL/naive_bus_router.sv
  E:/work-Lab/USTCRVSoC/hardware/RTL/ram.sv
  E:/work-Lab/USTCRVSoC/hardware/RTL/ram_bus_wrapper.sv
  E:/work-Lab/USTCRVSoC/hardware/RTL/soc_top.sv
  E:/work-Lab/USTCRVSoC/hardware/RTL/uart_rx.sv
  E:/work-Lab/USTCRVSoC/hardware/RTL/uart_tx_line.sv
  E:/work-Lab/USTCRVSoC/hardware/RTL/user_uart_tx.sv
  E:/work-Lab/USTCRVSoC/hardware/RTL/video_ram.sv
  E:/work-Lab/USTCRVSoC/hardware/Vivado/nexys4/USTCRVSoC-nexys4/USTCRVSoC-nexys4.srcs/sources_1/Nexys4_USTCRVSoC_top.sv
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/work-Lab/USTCRVSoC/hardware/Vivado/nexys4/USTCRVSoC-nexys4/USTCRVSoC-nexys4.srcs/constrs_1/Nexys-A7-100T-Master.xdc
set_property used_in_implementation false [get_files E:/work-Lab/USTCRVSoC/hardware/Vivado/nexys4/USTCRVSoC-nexys4/USTCRVSoC-nexys4.srcs/constrs_1/Nexys-A7-100T-Master.xdc]


synth_design -top Nexys4_USTCRVSoC_top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Nexys4_USTCRVSoC_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Nexys4_USTCRVSoC_top_utilization_synth.rpt -pb Nexys4_USTCRVSoC_top_utilization_synth.pb"
